apiVersion: v1
data:
  WORDPRESS_DB_HOST: bXlzcWw=
  WORDPRESS_DB_NAME: d29yZHByZXNz
  WORDPRESS_DB_PASSWORD: d29yZHByZXNz
  WORDPRESS_DB_USER: d29yZHByZXNz
kind: Secret
metadata:
  creationTimestamp: null
  name: wordpress
  namespace: dev
